NAME = multiple

targets = egl

objs =	../common/texture_milkyway.o ../common/esTransform.o \
	../common/cube_mesh.o ../common/companion_texture_flat.o \
	../common/companion_mesh.o ../common/companion_texture.o \
	../common/companion_array.o

include ../Makefile.test
