.PHONY : egl egl_install egl_run egl_wrap

EGL_LOG = /sdcard/egl.wrap.log
EGL_BMP = /sdcard/egl.wrap.BMP
EGL_OBJS = egl.o $(objs)

ifeq ($(OS), android)
	LIBS = -lEGL_mali -lGLESv2_mali
else
	LIBS = -lEGL -lGLESv2
endif

egl: egl_$(NAME)

egl_$(NAME): $(EGL_OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)

egl_install: egl_$(NAME)
	$(INSTALL) egl_$(NAME) $(INSTALL_DIR)/egl/$(NAME)

egl_wrap:
ifeq ($(OS),android)
	$(ADB) shell "rm $(EGL_BMP)"
	$(ADB) shell "rm $(EGL_LOG)"
	$(ADB) shell "LD_PRELOAD=libMali_wrap.so LIMA_WRAP_LOG=$(EGL_LOG) $(INSTALL_DIR)/egl/$(NAME)"
	$(ADB) pull $(EGL_LOG)
	$(ADB) pull $(EGL_BMP)
else
	$(shell LD_PRELOAD=libMali_wrap.so LIMA_WRAP_LOG=$(EGL_LOG) $(INSTALL_DIR)/egl/$(NAME))
endif

egl_run: $(ADB)
ifeq ($(OS),android)
	$(ADB) shell $(INSTALL_DIR)egl/$(NAME)
else
	$(shell $(INSTALL_DIR)/egl/$(NAME)"
endif

egl_clean:
	rm -f egl_$(NAME)

-include $(EGL_OBJS:%.o=%.P)
