.PHONY : limare install run wrap

LIMARE_LOG = /sdcard/limare.wrap.log

limare: limare_$(NAME)

limare_$(NAME): limare.c
	$(CC) $(CFLAGS) -o $@ $^ -llimare

install: $(ADB) limare_$(NAME)
	$(ADB) push limare_$(NAME) $(INSTALL_DIR)/limare/$(NAME)

wrap: $(ADB)
	$(ADB) shell "rm /sdcard/limare.bmp"
	$(ADB) shell "rm $(LIMARE_LOG)"
	$(ADB) shell "LD_PRELOAD=libMali_wrap.so LIMA_WRAP_LOG=$(LIMARE_LOG) $(INSTALL_DIR)/limare/$(NAME)"
	$(ADB) pull $(LIMARE_LOG)
	$(ADB) pull /sdcard/limare.bmp

run: $(ADB)
	$(ADB) shell $(INSTALL_DIR)limare/$(NAME)

clean:
	rm -f limare_$(NAME)
