.PHONY : egl egl_install egl_run egl_wrap

EGL_LOG = /sdcard/egl.wrap.log

egl: egl_$(NAME)

egl_$(NAME): egl.c
	$(CC) $(CFLAGS) -o $@ $^ -lEGL_mali -lGLESv2_mali

egl_install: $(ADB) egl_$(NAME)
	$(ADB) push egl_$(NAME) $(INSTALL_DIR)/egl/$(NAME)

egl_wrap: $(ADB)
	$(ADB) shell "rm $(EGL_LOG)"
	$(ADB) shell "rm /sdcard/lima.wrap.bmp"
	$(ADB) shell "LD_PRELOAD=libMali_wrap.so LIMA_WRAP_LOG=$(EGL_LOG) $(INSTALL_DIR)/egl/$(NAME)"
	$(ADB) pull $(EGL_LOG)
	$(ADB) pull /sdcard/lima.wrap.bmp

egl_run: $(ADB)
	$(ADB) shell $(INSTALL_DIR)egl/$(NAME)

egl_clean:
	rm -f egl_$(NAME)
