.PHONY : limare limare_install limare_run limare_wrap

LIMARE_LOG = /sdcard/limare.wrap.log
LIMARE_BMP = /sdcard/limare.wrap.bmp

limare: limare_$(NAME)

limare_$(NAME): limare.c $(objs)
	$(CC) $(CFLAGS) -o $@ $^ -L$(TOP)/limare/lib/ -llimare

limare_install: limare_$(NAME)
	$(INSTALL) limare_$(NAME) $(INSTALL_DIR)/limare/$(NAME)

limare_wrap:
ifeq ($(OS),android)
	$(ADB) shell "rm $(LIMARE_BMP)"
	$(ADB) shell "rm $(LIMARE_LOG)"
	$(ADB) shell "LD_PRELOAD=libMali_wrap.so LIMA_WRAP_LOG=$(LIMARE_LOG) $(INSTALL_DIR)/limare/$(NAME)"
	$(ADB) pull $(LIMARE_LOG)
	$(ADB) pull $(LIMARE_BMP)
else
	$(shell LD_PRELOAD=libMali_wrap.so LIMA_WRAP_LOG=$(LIMARE_LOG) $(INSTALL_DIR)/limare/$(NAME))
endif

limare_run:
ifeq ($(OS),android)
	$(ADB) shell $(INSTALL_DIR)limare/$(NAME)
else
	$(shell $(INSTALL_DIR)/limare/$(NAME)"
endif

limare_clean:
	rm -f limare_$(NAME)
