include ../Makefile.top

NAME = cube

all: premali egl

egl_cube: egl.c esTransform.c

premali_cube: premali.c esTransform.c

include ../Makefile.premali
include ../Makefile.dump
include ../Makefile.egl
