include ../Makefile.top

NAME = cube

all: limare egl

egl_cube: egl.c esTransform.c

limare_cube: limare.c esTransform.c

include ../Makefile.premali
include ../Makefile.dump
include ../Makefile.egl
