.PHONY : dump install run wrap

dump: limare_dump

limare_dump: dump.c dumped_stream.c
	$(CC) $(CFLAGS) -o $@ dump.c -lpremali

dump_install: $(ADB) limare_dump
	$(ADB) push limare_dump $(INSTALL_DIR)/limare/dump

dump_wrap: $(ADB)
	$(ADB) shell "rm /sdcard/premali.bmp"
	$(ADB) shell "rm $(WRAP_LOG)"
	$(ADB) shell "LD_PRELOAD=libMali_wrap.so REMALI_WRAP_LOG=$(WRAP_LOG) $(INSTALL_DIR)/limare/dump"
	$(ADB) pull $(WRAP_LOG)
	$(ADB) pull /sdcard/premali.bmp

dump_run: $(ADB)
	$(ADB) shell $(INSTALL_DIR)limare/dump

dump_clean:
	rm -f limare_$(NAME)
