.PHONY : dump install run wrap

dump: premali_dump

premali_dump: dump.c dumped_stream.c
	$(CC) $(CFLAGS) -o $@ dump.c -lpremali

dump_install: $(ADB) premali_dump
	$(ADB) push premali_dump $(INSTALL_DIR)/premali/dump

dump_wrap: $(ADB)
	$(ADB) shell "rm /sdcard/premali.bmp"
	$(ADB) shell "rm $(WRAP_LOG)"
	$(ADB) shell "LD_PRELOAD=libMali_wrap.so REMALI_WRAP_LOG=$(WRAP_LOG) $(INSTALL_DIR)/premali/dump"
	$(ADB) pull $(WRAP_LOG)
	$(ADB) pull /sdcard/premali.bmp

dump_run: $(ADB)
	$(ADB) shell $(INSTALL_DIR)premali/dump

dump_clean:
	rm -f premali_$(NAME)
