.PHONY : dump install run wrap

dump: premali_$(NAME)

premali_$(NAME): dump.c dumped_stream.c
	$(CC) $(CFLAGS) -o $@ dump.c -lpremali

install: $(ADB) premali_$(NAME)
	$(ADB) push premali_$(NAME) $(INSTALL_DIR)/premali/$(NAME)

wrap: $(ADB)
	$(ADB) shell "rm /sdcard/premali.bmp"
	$(ADB) shell "rm $(WRAP_LOG)"
	$(ADB) shell "LD_PRELOAD=libMali_wrap.so REMALI_WRAP_LOG=$(WRAP_LOG) $(INSTALL_DIR)/premali/$(NAME)"
	$(ADB) pull $(WRAP_LOG)
	$(ADB) pull /sdcard/premali.bmp

run: $(ADB)
	$(ADB) shell $(INSTALL_DIR)premali/$(NAME)

clean:
	rm -f premali_$(NAME)
