.PHONY : limare install run wrap

limare: limare_$(NAME)

limare_$(NAME): limare.c
	$(CC) $(CFLAGS) -o $@ $^ -lpremali

install: $(ADB) limare_$(NAME)
	$(ADB) push limare_$(NAME) $(INSTALL_DIR)/limare/$(NAME)

wrap: $(ADB)
	$(ADB) shell "rm /sdcard/premali.bmp"
	$(ADB) shell "rm $(WRAP_LOG)"
	$(ADB) shell "LD_PRELOAD=libMali_wrap.so REMALI_WRAP_LOG=$(WRAP_LOG) $(INSTALL_DIR)/limare/$(NAME)"
	$(ADB) pull $(WRAP_LOG)
	$(ADB) pull /sdcard/premali.bmp

run: $(ADB)
	$(ADB) shell $(INSTALL_DIR)limare/$(NAME)

clean:
	rm -f limare_$(NAME)
